### ISSUE TITLE
Relicense to GPLv2 or later

### ISSUE THREAD

**Issue by tbm** [beancount/beancount2ledger#1]
I'd like to distribute beancount2ledger under GPLv2 or later.  Beancount is GPLV2 only.

@blais can you give permission to re-license your code (the bean-report ledger/hledger related code) under GPLv2 or later.

**Comment by blais** [comment]
Sure! Go for it, convert it to GPLv2 or later.

**Comment by tbm** [comment]
Thank you, @blais!
