### ISSUE TITLE
Converter to Ledger should preserve tags (was: beancount to ledger)

### ISSUE THREAD

**Issue by blais** [beancount/beancount2ledger#3]
**[Original report](https://bitbucket.org/blais/beancount/issue/327) by Vikas Rawal (Bitbucket: [vikasrawal](https://bitbucket.org/vikasrawal), GitHub: [vikasrawal](https://github.com/vikasrawal)).**

----------------------------------------

Using the following command to convert a beancount file to ledger results in stripping the file of all tags.

> bean-report test.beancount ledger

It would be useful to retain the tags and make them ledger compatible.

Vikas

**Comment by blais** [comment]
**Original comment by Alen Šiljak (Bitbucket: Alen Siljak, GitHub: [MisterY](https://github.com/MisterY)).**

----------------------------------------

Either this or having full file compatibility (at least for the features supported by beancount) would be really helpful.

**Comment by blais** [comment]
**Original comment by Alen Šiljak (Bitbucket: Alen Siljak, GitHub: [MisterY](https://github.com/MisterY)).**

----------------------------------------

@Vikas, do you have a test file that could be used?

**Comment by alensiljak** [comment]
Hi, @tbm, 

I (probably) meant that the full file compatibility would be great. If not, then at least the support for the features that Beancount has and which are also supported in Ledger. Looking back, I see that the comment is not all too useful. ;)

**Comment by tbm** [comment]
@MisterY I'll try to work on compatibility (where this is possible). If you're aware of specific issues, please open bugs with beancount samples. Thanks!

**Comment by tbm** [comment]
I wonder if @vikasrawal meant meta-data rather than tags.  Meta-data is indeed stripped, see #7.

**Comment by vikasrawal** [comment]
Ledger calls them metadata tags. But yes, I was referring to the meta data.

**Comment by tbm** [comment]
> Ledger calls them metadata tags. But yes, I was referring to the meta data.

Ok, thanks for the clarification.

**Comment by tbm** [comment]
@vikasrawal @MisterY I split out the ledger conversion from beancount into a standalone tool called beancount2ledger. Please give this a go.
