### ISSUE TITLE
PyYAML not declared as dependency

### ISSUE THREAD

**Issue by dahelb** [beancount/beancount2ledger#31]
PYYaml is used in the `cli.py` module without being set as a dependency in `setup.cfg` and `requirements.txt`.

This prevents the cli from running in environments where PYaml is not already installed.

`ModuleNotFoundError: No module named 'yaml'`

Step to reproduce:
Install current master branch in a fresh virtual environment and run `beancount2ledger` command.

**Comment by tbm** [comment]
Thanks!  Do you want to submit a PR?
