### ISSUE TITLE
Add support for ledger lot dates and notes to bean-report

### ISSUE THREAD

**Issue by blais** [beancount/beancount2ledger#5]
**[Original report](https://bitbucket.org/blais/beancount/issue/427) by Marin Bernard (Bitbucket: [marinbernard](https://bitbucket.org/marinbernard), GitHub: [marinbernard](https://github.com/marinbernard)).**

----------------------------------------

While **bean-report** supports the conversion of beancount lot expressions to ledger syntax, it currently discards lot dates and notes. The following transaction:

```
2020-01-01 open Assets:Bank
2020-01-01 open Expenses:Computers
2020-01-01 commodity COMPUTER
    format: "1, COMPUTER"

2020-01-01 commodity USD

option "operating_currency" "USD"

2020-02-01 * "Super Shop"  "New computer"
    Expenses:Computers       1 COMPUTER {900.00 USD, 2019-12-25, "DiscountedComputer"} @ 1100.00 USD
    Assets:Bank
```

Is currently rendered as:

```
account Assets:Bank                                    

account Expenses:Computers                             

commodity COMPUTER

commodity USD

2020-02-01 * Super Shop | New computer
  Expenses:Computers                    1 COMPUTER {900.00 USD} @ 1100.00 USD
  Assets:Bank                                      -900.00 USD
```

Since ledger also [supports lot dates/notes](https://www.ledger-cli.org/3.0/doc/ledger3.html#Lot-dates), **bean-report** should ideally include them in the output, like:

```
account Assets:Bank                                    

account Expenses:Computers                             

commodity COMPUTER

commodity USD

2020-01-01 * Super Shop | New computer
    Expenses:Computers  1 COMPUTER [2019-12-25] {900.00 USD} (ChristmasDiscountedComputer) @ 1100.00 USD
    Assets:Bank
```

This would actually make **bean-report** usable as a converter for complex journals full of lot annotations.

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

I have some pending fixes for ledger output that I have to clean up and submit.

I can probably fix this one as well.

‌

**Comment by tbm** [comment]
@marinbernard I split out the ledger conversion from beancount into a standalone tool called beancount2ledger. Please give this a go.
