### ISSUE TITLE
Be smarter about rounding entries

### ISSUE THREAD

**Issue by tbm** [beancount/beancount2ledger#9]
I'm seeing entries like, which I'm sure are not necessary, and actually make things worse:

```
  Equity:Rounding                                          0.00000000000000000000001 GBP
```

**Comment by tbm** [comment]
Here's a good test case:

```
2010-01-01 open Expenses:Postage
2010-01-01 open Liabilities:Credit-Card

2019-09-19 * "Postage"
  Expenses:Postage           3.90 EUR @@ 4.32 USD
  Liabilities:Credit-Card               -4.32 USD
```

becomes

```account Expenses:Postage

account Liabilities:Credit-Card

2019-09-19 * Postage
  Expenses:Postage                                              3.90 EUR @ 1.107692307692307692307692308 USD
  Liabilities:Credit-Card                                      -4.32 USD
  Equity:Rounding                     -0.000000000000000000000000001 USD
```

**Comment by tbm** [comment]
@blais do you by any chance remember why you added these rounding entries in the first place? Do you have a test case where they were useful?

As far as I can tell, they do more harm than good, but I'm curious to see a testcase where they are useful.

**Comment by blais** [comment]
https://github.com/beancount/beancount/blob/master/beancount/parser/options.py#L289

Remove the option and they should be gone.

**Comment by tbm** [comment]
@blais sorry for not giving enough context.  This is about the ledger output.  It adds Rounding entries explicitly:

```
          # Insert a posting to absorb the residual if necessary. This is
          # sometimes needed because Ledger bases its balancing precision on the
          # *last* number of digits used on that currency. This is believed to be
          # a bug, so instead, we simply insert a rounding account to absorb the
          # residual and precisely balance the transaction.
          entry = interpolate.fill_residual_posting(entry, ROUNDING_ACCOUNT)
```

But in my experience these rounding entries are counterproductive.  I'm curious if you have a testcase where they make sense.

**Comment by blais** [comment]
I don't remember.

**Comment by tbm** [comment]
I'm reopening this bug.  @blais this bug is against beancount2ledger.  It's a genuine bug that I need to fix (either by not generating these entries at all or only when they are needed), so please leave it open.  You can unsubscribe from the bug though.

**Comment by blais** [comment]
Sorry about that. If you want to undo the work of the option, I think there is metadata on the postings which were added by that code (and if not, we should tag those auto-inserted postings with metadata). You can iterate and simply remove those postings before doing the conversion. That code should be a patch to Beancount (e.g., remove_rounding_postings()?). Don't remove the postings based on just the account name because the user might use that account explicitly. Does that make sense?

**Comment by tbm** [comment]
I wonder if this is basically the same cause as https://github.com/beancount/beancount/issues/246

**Comment by tbm** [comment]
Ok, I've come up with an example where a rounding entry is needed.

Valid in beancount:

```
2010-01-01 open Expenses:Test
2010-01-01 open Assets:Bank

2020-01-10 * "Test"
  Expenses:Test                           4.990 USD
  Assets:Bank                            -4.990 USD

2020-01-10 * "Test: will fail in ledger due to precision of USD"
  Expenses:Test            150.75 THB @ 0.03344 USD
  Assets:Bank                             -5.04 USD
```

The second transaction will fail in ledger:

```
Unbalanced remainder is:
           0.001 USD
```
